### ISSUE TITLE
[ bug?] Error loading script: CoAdapter.py

### ISSUE THREAD

**Issue by byblo** [MC-E/SD-webui-CoAdapter#1]
Hello.

Got the following error at starting SDwebui:

Error loading script: CoAdapter.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\stable-diffusion-webui\extensions\SD-webui-CoAdapter\scripts\CoAdapter.py", line 53, in <module>
    subprocess.run(shlex.split(f'wget {url} -O {save_path}'))
  File "C:\Users\robocop\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\robocop\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\robocop\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2]

It seems it is failing for some reason to download the required models contained in:

urls = {
    'TencentARC/T2I-Adapter':[
        'third-party-models/body_pose_model.pth', 'third-party-models/table5_pidinet.pth',
        'models/coadapter-canny-sd15v1.pth',
        'models/coadapter-color-sd15v1.pth',
        'models/coadapter-sketch-sd15v1.pth',
        'models/coadapter-style-sd15v1.pth',
        'models/coadapter-depth-sd15v1.pth',
        'models/coadapter-fuser-sd15v1.pth',

    ],
    'runwayml/stable-diffusion-v1-5': ['v1-5-pruned-emaonly.ckpt'],
    'andite/anything-v4.0': ['anything-v4.5-pruned.ckpt', 'anything-v4.0.vae.pt'],
}

After installing them manually, the problem got fixed and the extension was available in the SDwebui web interface.

BTW, are these 3 files required for anything?
'runwayml/stable-diffusion-v1-5': ['v1-5-pruned-emaonly.ckpt'],
'andite/anything-v4.0': ['anything-v4.5-pruned.ckpt', 'anything-v4.0.vae.pt'],
(and why not using the *.safetensors versions?)

Thank you for the nice extension :)

**Comment by MC-E** [comment]
Thanks for your attention. Model checkpoints are automatically downloaded by wget https://github.com/MC-E/SD-webui-CoAdapter/blob/master/scripts/CoAdapter.py#:~:text=subprocess.run(shlex.split(f%27wget%20%7Burl%7D%20%2DO%20%7Bsave_path%7D%27)). Windows may not support this command.

 Yesh, these three files are required for anything.
